<?php
return [
	'type'			=> 'flat',
	'description'	=> 'personalised image with name and seat details',
	'base'			=> 'train/train_base.jpg',
	'width'			=> 600,
	'height'		=> 350,
	'background'	=> '#0070b0',
	'colour'		=> '#fff',
	'alignment'		=> 'center',
	'v_alignment'	=> 'top',
	'angle'			=> 0,
	'font'			=> 'LiberationSans-Regular.ttf',
	'overlays'    => [
		'intro' => [
			'type'				=> 'text',
			'content'			=> '{{intro}}',
			'size'				=> 18,
			'min_size'			=> 14,
			'x1'				=> 0,
			'y1'				=> 45,
			'x2'				=> 589,
			'y2'				=> 70,
		],
		'coach' => [
			'type'				=> 'text',
			'content'			=> 'coach {{coach}}',
			'font'				=> 'train/scoreboard.ttf',
			'size'				=> 70,
			'min_size'			=> 60,
			'angle'				=> 3,
			'x1'				=> 0,
			'y1'				=> 90,
			'x2'				=> 589,
			'y2'				=> 180,
		],
		'seat' => [
			'type'				=> 'text',
			'content'			=> 'seat {{seat}}',
			'font'				=> 'train/scoreboard.ttf',
			'size'				=> 44,
			'min_size'			=> 30,
			'angle'				=> 3,
			'x1'				=> 0,
			'y1'				=> 180,
			'x2'				=> 589,
			'y2'				=> 240,
		],
		'awaits' => [
			'type'				=> 'text',
			'content'			=> 'awaits...',
			'size'				=> 18,
			'min_size'			=> 14,
			'x1'				=> 0,
			'y1'				=> 260,
			'x2'				=> 589,
			'y2'				=> 285,
		],
	],
];
